#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

app_start:
    path: /netgoflix
    controller: App\Controller\StartController::entry
    
app_verwaltung:
    path: /netgoflix/verwaltung
    controller: App\Controller\VerwaltungController::entry
    
app_verwaltung_formular:
    path: /netgoflix/verwaltung/formular
    controller: App\Controller\FilmFormularController::entry
    
logout:
    path: /logout
    
app_favorit:
    path: /netgoflix/favorit
    controller: App\Controller\FavoritController::entry